### ISSUE TITLE
Polymer 3.0.2 error

### ISSUE THREAD

**Issue by ghost** [MartinsThiago/polymer-3-redux#1]
## I have updated  polymer version to 3.0.2 . this error has occurred.

```
WARNING in ./src/ui/util/AntiShadowElement.ts
2:39-53 "export 'Element' (imported as 'PolymerElement') was not found in '@polymer/polymer/polymer-element'
 @ ./src/ui/util/AntiShadowElement.ts
 @ ./src/ui/components/TodoHeader.ts
 @ ./src/index.ts
 @ multi (webpack)-dev-server/client?http://localhost:7001 ./src/index.ts
```

**Comment by jagcolombat** [comment]
Hi troyageyna, in **./src/ui/util/AntiShadowElement.ts**, change this line 
`import {Element as PolymerElement} from "@polymer/polymer/polymer-element";`
for this
`import {PolymerElement} from "@polymer/polymer/polymer-element";`

From latest preview `@polymer/polymer/polymer-element` export `PolymerElement`

**Comment by LiberQuack** [comment]
I'll try to fix it on this weekend

Also I've been working with LitElement, soon I am going to create a repo **LitElement-Redux-Ts** with proper helps for getting values from forms into our components

**Comment by LiberQuack** [comment]
Late, but fixed :sweat_smile:
